In [107]:
import numpy as np

### 스핀 행렬

In [108]:
def func1(L):
    data = np.random.choice([-1, 1], size=(L, L)) # -1과 1 중에서 무작위로 LxL 개 뽑음
    return data

In [109]:
# 코드 작성에 활용할 연습용 데이터 beta
beta = func1(5)
print(beta)

[[ 1 -1 -1 -1  1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1  1]
 [ 1 -1  1  1 -1]
 [-1  1  1 -1 -1]]


### 각 노드의 이웃 노드

In [110]:
def neighbor(array, n): # n번째 노드의 이웃 노드 인덱스(상하좌우 4개)를 찾음
    L, _ = array.shape

    # 상
    up = n-L # 윗쪽으로 한 칸 이동
    if up < 0: # 이동 전이 맨 윗쪽 열인 경우,
        up += L*L # 아랫쪽으로 L칸 이동하여 주기적 경계 조건 만족

    # 하
    down = n+L # 아랫쪽으로 한 칸 이동
    if down >= L*L: # 이동 전이 맨 아랫쪽 열인 경우,
        down -= L*L # 윗쪽으로 L칸 이동하여 주기적 경계 조건 만족

    # 좌
    left = n-1 # 왼쪽으로 한 칸 이동
    if (left+1)%L == 0: # 이동 전이 맨 왼쪽 열인 경우,
        left += L # 오른쪽으로 L칸 이동(= 아래로 한 칸 이동)하여 주기적 경계 조건 만족
    # 우
    right = n+1 # 오른쪽으로 한 칸 이동
    if right%L == 0: # 이동 후가 맨 왼쪽 열(= 이동 전이 맨 오른쪽 열)인 경우,
        right -= L # 왼쪽으로 L칸 이동(= 위로 한 칸 이동)하여 주기적 경계 조건 만족

    return [up, down, left, right] # 이웃 노드의 인덱스 리스트(상하좌우 순) 출력

In [111]:
neighbor(beta, 9) # 5x5 행렬 9번 노드의 이웃: [4, 14, 8, 5]

[4, 14, 8, 5]

### 각 노드의 에너지

In [112]:
def func2(array, n):
    array_list = [item for sublist in array for item in sublist] # 행렬을 하나의 리스트로
    e = 0 # 에너지 초기화

    neighbors = neighbor(array, n) # neighbors: n번째 노드의 이웃 노드 리스트

    for i in neighbors:
        if array_list[n] == array_list[i]: # n번째 노드와 이웃 노드가 같은 스핀일 경우
            e -= 1 # -1을 sum
        else: # 다른 스핀일 경우
            e += 1 # +1을 sum

    return e # n번째 노드가 갖는 총 에너지 반환

In [113]:
func2(beta, 9) # 5x5 행렬 9번 노드의 에너지

2

### 행렬의 총 에너지

In [114]:
def E(array):
    N = len(array)**2 # N = L x L
    result = []

    for i in range(0,N): # 0~(N-1)번째 노드를 반복하여
        result.append(func2(array, i)) # 각 노드의 총 에너지를 저장

    return sum(result)/2 # 각 노드의 총 에너지를 모두 더한 후, (a,b)와 (b,a)의 중복 제거를 위해 2로 나누어 반환

In [115]:
E(beta)

6.0

### 새로운 데이터로 테스트

In [116]:
test = func1(5)
print(test)
E(test)

[[-1 -1 -1  1  1]
 [ 1 -1 -1  1 -1]
 [ 1 -1 -1  1  1]
 [-1  1  1 -1  1]
 [ 1  1  1  1  1]]


-2.0